jobs:
  grpcGoServer:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      dockerImageName: go-grpc-server
      dockerContextDirectory: src/BenchmarksApps/Grpc/GoServer/
      dockerFile: src/BenchmarksApps/Grpc/GoServer/Dockerfile
    readyStateText: Application started
    waitForExit: false
    options:
      requiredOperatingSystem: linux
