variables:
  headers:
    none: ''
    plaintext: "--header Accept:text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7 --header Connection:keep-alive"
    connectionclose: "--header Connection:close"
  presetHeaders: none

jobs:
  bombardier:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: master
      project: src/BombardierClient/BombardierClient.csproj
    readyStateText: Bombardier Client
    sdkVersion: 3.0.100
    aspNetCoreVersion: '3.0'
    runtimeVersion: '3.0'
    waitForExit: true
    variables:
      connections: 256
      duration: 5
      rate: 0
      transport: # fasthttp | http1 | http2
    arguments: "-c {{connections}} {{serverUri}}:{{serverPort}}{{path}} -d {{duration}}s -l {% if rate != 0 %} --rate {{ rate }} {% endif %} {% if transport != '' %} --{{ transport}} {% endif %} {{headers[presetHeaders]}}"
